import java.awt.*;
import java.util.ArrayList;

/**
 * Created by Matthias on 17.05.2015.
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditorUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jColorButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSizeSlider = new javax.swing.JSlider(Min_Size,Max_Size,Size_INIT);
        jLabel1 = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 378, Short.MAX_VALUE)
        );

        jCheckBox1.setText("mit Linie Verbinden");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });


        jColorButton.setText("Farbe Anwenden");
        jColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorButtonMouseClicked(evt);
            }
        });

        jSizeSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSizeSliderMouseClicked(evt);
            }
        });
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        jLabel1.setText("Grösse der Punkte");

        jLabel2.setText("Y - Achse");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Variable 1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Variable 2");

        jLabel3.setText("X - Achse");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Variable 1");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Variable 2");

        jMenu1.setText("Datei");

        jMenuItem1.setText("Neue Datei");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Beenden");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(jCheckBox1)
                                                                        .addGap(29, 29, 29))
                                                                .addComponent(jSizeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel1))
                                                        .addComponent(jLabel2)
                                                        .addComponent(jRadioButton1)
                                                        .addComponent(jRadioButton2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jRadioButton3)
                                                        .addComponent(jRadioButton4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jColorButton)
                                                .addGap(233, 233, 233))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)
                                                .addGap(4, 4, 4)
                                                .addComponent(jRadioButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCheckBox1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel1)
                                                .addGap(2, 2, 2)
                                                .addComponent(jSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jColorButton))
                                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


        pack();
    }
    Color color = Color.BLUE;

    // Event Handlers;
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        if( jCheckBox1.isSelected()){
            linesActivated = true;
            deleteOnPanel1();
            coordinateslines.clear();
            drawOnPanel1();
        }
        else{
            linesActivated = true;
            deleteOnPanel1();
            linesActivated = false;
            coordinateslines.clear();
            drawOnPanel1();

        }
    }

    private void jSizeSliderMouseClicked(java.awt.event.MouseEvent evt) {
        deleteOnPanel1();
        width = jSizeSlider.getValue();
        jSizeSlider.setValue(width);
        coordinateslines.clear();
        drawOnPanel1();

    }
    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {
        deleteOnPanel1();
        coordinateslines.clear();
        drawOnPanel1();
    }
    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {
        deleteOnPanel1();
        coordinateslines.clear();
        drawOnPanel1();
    }
    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {
        deleteOnPanel1();
        coordinateslines.clear();
        drawOnPanel1();

    }
    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {
        deleteOnPanel1();
        coordinateslines.clear();
        drawOnPanel1();
    }
    private void jColorButtonMouseClicked(java.awt.event.ActionEvent evt) {
        color = jColorChooser1.getColor();
        coordinateslines.clear();
        deleteOnPanel1();
        drawOnPanel2();
        drawOnPanel1();
        drawOnPanel2();
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        ActionNewFile coordinates1 = NewAction();
        coordinates = coordinates1.getCoordinates();
        coordinates1.getFactorV2X();
        factorV1X = coordinates1.getFactorV1X();
        factorV1Y = coordinates1.getFactorV1Y();
        factorV2X = coordinates1.getFactorV2X();
        factorV2Y = coordinates1.getFactorV2Y();
        int cnt =0;
        while(cnt<coordinates.size()){
            coordinateslines.add(400+Math.round(factorV1X*coordinates.get(cnt)));
            coordinateslines.add(250-Math.round(factorV2Y*coordinates.get(cnt+1)));
            cnt= cnt+2;
        }
        String nameVariable1 = coordinates1.getNameVariable1();
        String nameVariable2 = coordinates1.getNameVariable2();
        jRadioButton1.setText(nameVariable1);
        jRadioButton1.setSelected(false);
        jRadioButton2.setText(nameVariable2);
        jRadioButton2.setSelected(true);
        jRadioButton3.setText(nameVariable1);
        jRadioButton3.setSelected(true);
        jRadioButton4.setText(nameVariable2);
        jRadioButton4.setSelected(false);
        drawOnPanel1();
        drawOnPanel2();
        System.out.println(panel1.getHeight());
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }
    private ActionNewFile NewAction(){
        ActionNewFile NewAction = new ActionNewFile();
        return NewAction;

    }
    public void deleteOnPanel1(){
        panel1.clearPanel1();
    }
    public void deleteOnPanel2(){
        jPanel2.clearPanel2();
    }
    public void drawOnPanel1() {
        if (jRadioButton1.isSelected() && jRadioButton4.isSelected()) {
            int cnt1 = 0;
            while(cnt1<coordinates.size()){
                coordinateslines.add(400+Math.round((factorV2X*coordinates.get(cnt1+1))));
                coordinateslines.add(350-Math.round((factorV1Y*coordinates.get(cnt1))));
                cnt1= cnt1+2;
            }
            int cnt = 0;
            while (cnt < coordinates.size()) {
                int y = 350-Math.round((factorV1Y*coordinates.get(cnt)));
                int x = 400+Math.round((factorV2X*coordinates.get(cnt+1)));
                int height = width;
                circle = makeCircle(x - height / 2, y - width / 2, height, width, color, linesActivated, coordinateslines);
                panel1.addCircle(circle);
                cnt = cnt +2;
            }
        }
        if(jRadioButton2.isSelected() && jRadioButton3.isSelected() ) {
            int cnt1 = 0;
            while(cnt1<coordinates.size()) {
                coordinateslines.add(400 + Math.round((factorV1X*coordinates.get(cnt1))));
                coordinateslines.add(350 - Math.round((factorV2Y*coordinates.get(cnt1+1))));
                cnt1 = cnt1 + 2;
            }
            int cnt = 0;
            while (cnt < coordinates.size()) {
                int x =400+ Math.round((factorV1X*coordinates.get(cnt)));
                int y =350- Math.round((factorV2Y*coordinates.get(cnt+1)));
                int height = width;
                circle = makeCircle(x - height / 2, y - width / 2, height, width, color, linesActivated, coordinateslines);
                panel1.addCircle(circle);
                cnt = cnt + 2;
            }
        }
        if(jRadioButton1.isSelected() && jRadioButton3.isSelected() ) {
            int cnt1 = 0;
            while(cnt1<coordinates.size()) {
                coordinateslines.add(400 + Math.round((factorV1X*coordinates.get(cnt1))));
                coordinateslines.add(350 - Math.round((factorV1Y*coordinates.get(cnt1))));
                cnt1 = cnt1 + 2;
            }
            int cnt = 0;
            while (cnt < coordinates.size()) {

                int x = 400 +Math.round((factorV1X*coordinates.get(cnt)));
                int y = 350-Math.round((factorV1Y*coordinates.get(cnt)));

                int height = width;
                circle = makeCircle(x - height / 2, y - width / 2, height, width, color, linesActivated, coordinateslines);

                panel1.addCircle(circle);
                cnt = cnt + 2;
            }
        }
        if(jRadioButton2.isSelected() && jRadioButton4.isSelected() ) {
            int cnt1 = 0;
            while(cnt1<coordinates.size()) {
                coordinateslines.add(400 + Math.round((factorV2X*coordinates.get(cnt1+1))));
                coordinateslines.add(350 - Math.round((factorV2Y*coordinates.get(cnt1+1))));
                cnt1 = cnt1 + 2;
            }
            int cnt = 0;
            while (cnt < coordinates.size()) {

                int y = 400 + Math.round((factorV2Y*coordinates.get(cnt+1)));
                int x = 350 -Math.round((factorV2X*coordinates.get(cnt+1)));

                int height = width;
                circle = makeCircle(x - height / 2, y - width / 2, height, width, color, linesActivated, coordinateslines);
                panel1.addCircle(circle);
                cnt = cnt + 2;
            }
        }

    }

    public void drawOnPanel2(){
        histogram = makeHistogram(coordinates,color);
        jPanel2.addHistogram(histogram);
    }

    public static Histogram makeHistogram(ArrayList<Float> coordinates, Color color){
        Histogram newHistogram = new Histogram(coordinates, color);
        return newHistogram;
    }
    public static Circle makeCircle(int x, int y, int width, int height, Color color, Boolean linesActivated, ArrayList<Integer> coordinates) {
        Circle newCircle = new Circle(x,y,width,height,color,linesActivated, coordinates);
        return newCircle;
    }
    // Variables declaration - do not modify
    ArrayList<Float> coordinates;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private DrawingOnPanel1 panel1 = new DrawingOnPanel1();
    private DrawingOnPanel2 jPanel2 = new DrawingOnPanel2();
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSizeSlider;
    private javax.swing.JButton jColorButton;
    static final int Min_Size = 1;
    static final int Max_Size = 40;
    static final int Size_INIT = 10;
    float factorV1X;
    float factorV1Y;
    float factorV2X;
    float factorV2Y;
    ArrayList<Integer> coordinateslines = new ArrayList<Integer>();
    int width = 10;
    Circle circle;
    Histogram histogram;
    private Boolean linesActivated = false;
    // End of variables declaration


}